#!/bin/bash

METRIC_PATH=$(echo "$(dirname $0)/${0}" | sed -e 's@/@.@g' -e 's@^\.@@' -e 's@\.\.@._dot_.@g')
METRIC_VALUE=${1-1000}
METRIC_TIMESTAMP=$(date +%s)

echo -e "${METRIC_PATH:?}\t${METRIC_VALUE:?}\t${METRIC_TIMESTAMP:?}"
